app/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User, Influencer, Sponsor, Category
from . import db


auth = Blueprint("auth", __name__)


@auth.route("/signup", methods=['GET', 'POST'])
def sign_up():
    if current_user.is_authenticated:
        flash("You are already logged in !", category="warning")
        return redirect("/")
    
    options = Category.query.all()
    
    if request.method == "POST":
        username = request.form.get("username")
        email = request.form.get("email")

        flag = True
        if User.query.filter_by(email=email).first():
            flag = False
            flash("This Email ID already exists !", category="danger")
        elif User.query.filter_by(username=username).first():
            flag = False
            flash("This Username is not available !", category="danger")

        role = request.form.get("role")
        password = request.form.get("password")

        if role == "influencer":
            name = request.form.get("full_name")
            niche = request.form.get("niche")
            if not flag:
                return render_template("sign-up.html", full_name=name, niche=niche, role=role, username=username, email=email, options=options)
            
            user = User(username=username, email=email, password=generate_password_hash(password), role=role)
            influencer = Influencer(username=username, name=name, niche=niche)

            db.session.add(user)
            db.session.add(influencer)
            
        else:
            name = request.form.get("company_name")
            industry = request.form.get("industry")
            if not flag:
                return render_template("sign-up.html", company_name=name, industry=industry, role=role, username=username, email=email, options=options)

            user = User(username=username, email=email, password=generate_password_hash(password), role=role)
            sponsor = Sponsor(username=username, name=name, industry=industry)

            db.session.add(user)
            db.session.add(sponsor)


        db.session.commit()
        flash("Account Created Successfully !", category="success")
        return redirect(url_for("auth.login"))
        
    return render_template("sign-up.html", options=options)


@auth.route("/login", methods=['GET', 'POST'])
def login():
    next_page = request.args.get("next", "/")
    if current_user.is_authenticated:
        flash("You are already logged in !", category="warning")
        return redirect(next_page)
    
    if request.method == "POST":
        username = request.form.get("username", "")
        password = request.form.get("password", "")
        user = User.query.filter_by(username=username).first()
        if not user:
            flash("User does not exists with this credentials !", category="danger")
            return render_template("login.html", username=username)
        
        if not check_password_hash(user.password, password):
            flash("Incorrect Password !", category="danger")
            return render_template("login.html", username=username)
        
        flash("Logged In Successfully !", category="success")
        login_user(user, remember=True)
        return redirect(next_page)
    return render_template("login.html")


# @auth.route("/admin/login", methods=['GET', 'POST'])
# def admin_login():
#     next_page = request.args.get("next", "/")
#     if current_user.is_authenticated:
#         flash("You are already logged in !", category="warning")
#         return redirect(next_page)
    
#     if request.method == "POST":
#         username = request.form.get("username", "")
#         password = request.form.get("password", "")
#         user = User.query.filter_by(username=username).first()
#         if not user:
#             flash("User does not exists with this credentials !", category="danger")
#             return render_template("admin_login.html", username=username)
        
#         if not check_password_hash(user.password, password):
#             flash("Incorrect Password !", category="danger")
#             return render_template("admin_login.html", username=username)
        
#         flash("Logged In Successfully !", category="success")
#         login_user(user, remember=True)
#         return redirect("/")
#     return render_template("admin_login.html")


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    flash("Logged Out !", category="success")
    return redirect(url_for("auth.login"))

app/templates/admin_all_admins.html
{% extends 'admin_base.html' %}
{% block title %}All Admins{% endblock title %}
{% block body %}
    <div id="container">
        <h1 align="center" class="mb-5">All Admins</h1>
        <div id="add_admin" class="panel ms-5" style="width: 40%; float: left;">
            <h2 align="center">Add Admin</h2>
            <br><br>
            <form method="POST">
                <label for="name" class="form-label">Name</label>
                <input type="text" id="name" name="name" value="{{ name }}" class="form-control" required>
                <br>
                <label for="username" class="form-label">Username</label>
                <input type="text" id="username" name="username" value="{{ username }}" class="form-control" minlength="4" required>
                <br>
                <label for="email" class="form-label">Email ID</label>
                <input type="email" id="email" name="email" value="{{ email }}" class="form-control" required>
                <br>
                <label for="password" class="form-label">Password</label>
                <input type="password" id="password" name="password" class="form-control" required>
                <br>
                <label for="confirm_password" class="form-label">Confirm Password</label>
                <input type="password" id="confirm_password" name="confirm_password" class="form-control" required>
                <br>
                <button type="submit" class="btn btn-outline-dark" onclick="return validate()">Add Admin</button>
            </form>
        </div>
        <div id="all_admins" style="width: 45%; float: right;">
            <h2 align="center" class="me-5">Active Admins</h2>
            <br><br>
            {% if admins %}
                <div class="row">
                    {% for admin in admins %}
                        <div class="col-md-6 mb-5">
                            <div class="card" style="width: 15rem; align-items: center; text-align: center;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ admin.name }}</h5>
                                    <p class="card-text">@{{ admin.username }}</p>
                                </div>
                                <div class="card-body">
                                    <form method="POST" action="{{ url_for('admin.flag_user', username=admin.username) }}">
                                        <button type="submit" class="btn btn-outline-danger">Revoke Admin</button>
                                    </form>
                                </div>
                            </div>
                        </div>  
                    {% endfor %}
                </div>
            {% else %}
                <div class="d-flex justify-content-center" style="margin-top: 120px;">
                    <span>No Admins !</span>
                </div>
            {% endif %}
        </div>
    </div>
    <script>
        function validate() {
            const messages = document.getElementById("js_messages");

            const password = document.getElementById("password").value;
            const confirm_password = document.getElementById("confirm_password").value;

            if (password != confirm_password) {
                messages.style.display = "block";
                let message = "Passwords do not match !";
                messages.innerHTML = `<div class="alert alert-danger alert-dismissible fade show sticky-top" role="alert">
                                        ${message}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                    </div>`
                return false;
            }
            
            return true;
        }
    </script>
{% endblock body %}

app/templates/admin_campaign_view.html
{% extends 'admin_base.html' %}
{% block title %}Campaign Details{% endblock title %}
{% block body %}
    <div id="container">
        <h1 align="center">Campaign Details</h1>
        {% if campaign.flagged %}
            <div id="message" class="mt-5" style="text-align: center; align-content: center;">
                <img src="{{ url_for('static', filename='images/warning.png') }}" width="70px">
                <h3>Campaign has been <span class="text-danger">Flagged</span> by Admin !</h3>
            </div>
        {% endif %}
        <div id="campaign" class="d-flex justify-content-center">
            <table class="table table-striped mt-5" style="width: 50%;">
                <tr>
                    <th>Name</th>
                    <td>{{ campaign.name }}</td>
                </tr>
                <tr>
                    <th>Description</th>
                    <td>{{ campaign.description }}</td>
                </tr>
                <tr>
                    <th>Start Date</th>
                    <td>{{ campaign.start_date.strftime("%d %b, %Y") }}</td>
                </tr>
                <tr>
                    <th>End Date</th>
                    <td>{{ campaign.end_date.strftime("%d %b, %Y") }}</td>
                </tr>
                <tr>
                    <th>Budget</th>
                    <td>INR {{ campaign.budget }}</td>
                </tr>
                <tr>
                    <th>Visibility</th>
                    <td>{{ campaign.visibility }}</td>
                </tr>
                {% if campaign.influencer_id %}
                    <tr>
                        <th>Influencer</th>
                        <td>{{ Influencer.query.filter_by(id=campaign.influencer_id).first().name }} (@{{ Influencer.query.filter_by(id=campaign.influencer_id).first().username }})</td>
                    </tr>
                {% endif %}
                <tr>
                    <th></th>
                    <td>
                        <form method="POST" action="{{ url_for('admin.campaign_delete', id=campaign.id) }}">
                            <button type="submit" class="btn btn-outline-danger">Delete</button>
                        </form>
                    </td>
                </tr>
            </table>
        </div>
    </div>
{% endblock body %}

app/templates/admin_dashboard.html
{% extends 'admin_base.html' %}
{% block title %}Dashboard{% endblock title %}
{% block body %}
    <div id="container">
        <h1 align="center">Welcome {{ current_user.admin.name.split()[0] }}</h1>
        <div id="stats" class="mt-5">
            <div class="d-flex justify-content-center">
                <canvas id="users" style="width:100%; max-width:950px"></canvas>
            </div>
            <br><br>
            <div style="width: 47%; float: left;">
                <canvas id="campaigns" style="width:100%; max-width:700px"></canvas>
                <br>
                <div align="center"><span>Total Campaigns<br>{{ campaign_values | sum }}</span></div>
                <br><br>
                <canvas id="flagged_campaigns" style="width:100%; max-width:700px"></canvas>
                <br><br>
                <canvas id="sponsor_industry" style="width:100%; max-width:700px"></canvas>
            </div>
            <div style="width: 47%; float: right;">
                <canvas id="transactions" style="width:100%; max-width:700px"></canvas>
                <br>
                <div align="center">
                    <span>
                        Average Pay Amount
                        <br>
                        {% if transaction_values | length != 0 %}
                            INR {{ ((transaction_values | sum) / (transaction_values | length)) | round(2) }}
                        {% else %}
                            INR 0
                        {% endif %}
                    </span>
                </div>
                <br><br>
                <canvas id="campaign_status" style="width:100%; max-width:700px"></canvas>
                <br><br>
                <canvas id="influencer_niche" style="width:100%; max-width:700px"></canvas>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <script>
        var user_labels = {{ user_labels | tojson }};
        var user_values = {{ user_values | tojson }};
        new Chart("users", {
            type: "bar",
            data: {
                labels: user_labels,
                datasets: [{
                    data: user_values,
                    backgroundColor: user_values.map(() => randomizeColor())
                }]
            },
            options: {
                legend: {
                    display: false
                },
                title: {
                    display: true,
                    text: "Users Distribution"
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        },
                        scaleLabel: {
                            display: true,
                            labelString: "No. of Users"
                        }
                    }],
                    xAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: "Role"
                        }
                    }]
                }
            }
        });

        var campaign_labels = {{ campaign_labels | tojson}};
        var campaign_values = {{ campaign_values | tojson }};
        new Chart("campaigns", {
            type: "pie",
            data: {
                labels: campaign_labels,
                datasets: [{
                    data: campaign_values,
                    backgroundColor: ["green", "orange", "blue", "red"]
                }]
            },
            options: {
                title: {
                    display: true,
                    text: "Campaigns"
                }
            }
        });

        var transaction_labels = {{ transaction_labels | tojson }};
        var transaction_values = {{ transaction_values | tojson }};
        new Chart("transactions", {
            type: "bar",
            data: {
                labels: transaction_labels,
                datasets: [{
                    data: transaction_values,
                    backgroundColor: transaction_values.map(() => randomizeColor())
                }]
            },
            options: {
                legend: {
                    display: false
                },
                title: {
                    display: true,
                    text: "Transactions"
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        },
                        scaleLabel: {
                            display: true,
                            labelString: "Budget"
                        }
                    }],
                    xAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: "Completed Campaigns"
                        }
                    }]
                }
            }
        });

        var category_labels = {{ category_labels | tojson }};

        var i_values = {{ i_values | tojson }};
        new Chart("influencer_niche", {
            type: "bar",
            data: {
                labels: category_labels,
                datasets: [{
                    data: i_values,
                    backgroundColor: i_values.map(() => randomizeColor())
                }]
            },
            options: {
                legend: false,
                title: {
                    display: true,
                    text: "Influencer based on Niche"
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        },
                        scaleLabel: {
                            display: true,
                            labelString: "No. of Influencer"
                        }
                    }],
                    xAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: "Niche"
                        }
                    }]
                }
            }
        });

        var s_values = {{ s_values | tojson }};
        new Chart("sponsor_industry", {
            type: "bar",
            data: {
                labels: category_labels,
                datasets: [{
                    data: s_values,
                    backgroundColor: s_values.map(() => randomizeColor())
                }]
            },
            options: {
                legend: false,
                title: {
                    display: true,
                    text: "Sponsor based on Industry"
                },
                scales: {
                    yAxes: [{
                        ticks: {
                            beginAtZero: true
                        },
                        scaleLabel: {
                            display: true,
                            labelString: "No. of Sponsor"
                        }
                    }],
                    xAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: "Industry"
                        }
                    }]
                }
            }
        });

        var flagged_labels = {{ flagged_labels | tojson }}
        var flagged_values = {{ flagged_values | tojson }}
        new Chart("flagged_campaigns", {
            type: "doughnut",
            data: {
                labels: flagged_labels,
                datasets: [{
                    data: flagged_values,
                    backgroundColor: ["red", "green"]
                }]
            },
            options: {
                title: {
                    display: true,
                    text: "Flagged Campaigns"
                }
            }
        });
        
        var status_labels = {{ status_labels | tojson }}
        var status_values = {{ status_values | tojson }}
        new Chart("campaign_status", {
            type: "doughnut",
            data: {
                labels: status_labels,
                datasets: [{
                    data: status_values,
                    backgroundColor: status_values.map(() => randomizeColor())
                }]
            },
            options: {
                title: {
                    display: true,
                    text: "Campaign Visibility"
                }
            }
        });

        function randomizeColor() {
            const hex = "0123456789ABCDEF";
            let color_code = "#";
            for (i = 0; i < 6; i++) {
                color_code += hex[parseInt(Math.random() * 16)]
            }
            return color_code
        }
    </script>
{% endblock body %}

app/templates/admin_find_influencers.html
{% extends 'admin_base.html' %}
{% block title %}Find Influencer{% endblock title %}
{% block body %}
    <div id="container">
        <h1 align="center">Find Influencers</h1>
        <br><br>
        <div style="width: 20%; float: left;" class="m-3">
            <h3>Filters</h3>
            <br>
            <form method="GET">
                <label for="name" class="form-label">Username / Name</label>
                <input type="text" id="name" name="name" placeholder="Search by Name" value="{{ name }}" class="form-control">
                <br>
                <label for="niche" class="form-label">Niche</label>
                <select id="niche" name="niche" class="form-control">
                    <option value="">Select Niche</option>
                    {% for cat in categories %}
                        <option value="{{ cat.name }}" {% if cat.name == niche %} selected {% endif %}>{{ cat.name }}</option>
                    {% endfor %}
                </select>
                <br>
                <button type="submit" class="btn btn-outline-dark">Search</button>
            </form>
        </div>
        <div style="width: 65%; float: right;" class="me-5">
            {% if influencers %}
                <div class="row">
                    {% for i in influencers %}
                        <div class="col-md-4 mb-5">
                            <div class="card" style="width: 18rem; align-items: center; text-align: center;">
                                <img src="{{ url_for('static', filename=i.profile_picture) }}" width="200px" height="200px" class="mt-2" style="border-radius: 50%; object-fit: cover;" class="card-title">
                                <div class="card-body">
                                    <h5 class="card-title">{{ i.name }}</h5>
                                    <p class="card-text">@{{ i.username }}</p>
                                </div>
                                <ul class="list-group list-group-flush">
                                    <li class="list-group-item">Niche: {{ i.niche }}</li>
                                    {% if avg_ratings[i] %}
                                        <li class="list-group-item">Rating: {{ avg_ratings[i][0] }} <span class="text-muted" style="font-size: smaller;">({{ avg_ratings[i][1] }})</span></li>
                                    {% else %}
                                        <li class="list-group-item">Rating: -- <span class="text-muted" style="font-size: smaller;">(0)</span></li>
                                    {% endif %}
                                    <li class="list-group-item">Reach: {{ i.reach }}</li>
                                    <li class="list-group-item">
                                        Active Socials<br>
                                        {% if i.reach == 0 %}
                                            <span class="text-muted">No Socials added !</span>
                                        {% else %}
                                            {% for social in i.socials %}
                                                {% if i.socials[social] %}
                                                    <img src="{{ url_for('static', filename='images/' + social + '.png') }}" width="30px" class="m-1 mt-2">
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    </li>
                                </ul>
                                <div class="card-body">
                                    <form method="POST" action="{{ url_for('admin.flag_user', username=i.username) }}">
                                        <button type="submit" class="btn btn-outline-danger">Flag Influencer</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            {% else %}
                <div style="margin: 130px 0 0 220px;">
                    <span>No Results found !</span>
                    <br><br>
                    <a href="{{ url_for('admin.find_influencers') }}" class="btn btn-outline-secondary">Clear all filters</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

app/templates/flagged_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>Flagged by Admin</title>
</head>
<body>
    <div id="flashed_messages" class="text-center">
        <div id="js_messages" style="display: none;"></div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    <div id="container">
        <div id="message" style="margin-top: 120px; text-align: center; align-content: center;">
            <img src="{{ url_for('static', filename='images/warning.png') }}" width="120px">
            <br><br>
            <h1>You have been <span class="text-danger">Flagged</span> by Admin !</h1>
            <br>
            <h4 class="text-muted">Please contact Administrator for more Information.</h4>
        </div>
        <br><br>
        <div id="logout" class="d-flex justify-content-center">
            <a type="bytton" href="{{ url_for('auth.logout') }}" class="btn btn-outline-secondary">Log Out</a>
        </div>
    </div>
</body>
</html>

app/templates/sponsor_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <title>{% block title %}{% endblock title %} | Sponsor</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">  <!-- fixed-top -->
        <div class="container-fluid">
          <a class="navbar-brand" href="/">Sponsor Dashboard</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('sponsor.dashboard') }}">Dashboard</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('sponsor.campaigns') }}">Campaigns</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('sponsor.find') }}">Find</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('sponsor.transactions') }}">Transactions</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('sponsor.stats') }}">Stats</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('sponsor.profile') }}">Profile</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <div id="flashed_messages" class="text-center">
        <div id="js_messages" style="display: none;"></div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    </div>
    <!-- <br><br> -->
    {% block body %}        
    {% endblock body %}
</body>
</html>

app/templates/sponsor_transactions.html
{% extends 'sponsor_base.html' %}
{% block title %}Transactions{% endblock title %}
{% block body %}
    <div id="container">
        <div id="transactions" class="m-5">
            <h1 align="center">Transactions</h1>
            <div id="download_csv" align="right" class="mb-2">
                <form method="POST">
                    <button type="submit" class="btn btn-dark">Download</button>
                </form>
            </div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Transaction<br>ID</th>
                        <th scope="col">Campaign<br>Name</th>
                        <th scope="col">Influencer<br>Username</th>
                        <th scope="col">Pay Amount</th>
                        <th scope="col">Date</th>
                        <th scope="col">Time</th>
                        <th scope="col">Campaign<br>Details</th>
                    </tr>
                </thead>
                <tbody>
                    {% if transactions %}
                        {% for t in transactions[::-1] %}
                            <tr>
                                <td>{{ t.id }}</td>
                                <td>{{ t.campaign.name }}</td>
                                <td>{{ t.influencer.username }}</td>
                                <td>INR {{ t.amount }}</td>
                                <td>{{ t.date.strftime("%d %b, %Y") }}</td>
                                <td>{{ t.date.strftime("%H:%M:%S") }}</td>
                                <td><a href="{{ url_for('sponsor.campaign_view', id=t.campaign_id) }}" class="btn btn-outline-dark">View</a></td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td align="center" rowspan="2" colspan="7">No Transactions !</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock body %}